# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- main

name: 0.9$(Rev:.r)
pool:
  vmImage: 'windows-latest'

variables:
- name: SkipDecorator
  value: true 

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/feature/release-nugget

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: elephant    
    type: dotnet
    to: nuget
    nugetServiceConnection: Nuget.org Take  
    includeSymbols: true
    testParameters: --configuration Release --no-build --filter "Category=Memory"
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: elephant    
    type: dotnet
    to: nuget
    nugetServiceConnection: Nuget.org Take  
    includeSymbols: true
    wayParameter: